### ISSUE TITLE
archlinux firefox 44.0.2 lastpass toolbar icon not compatible

### ISSUE THREAD

**Issue by poplarch** [3marcusw/simplewhitecompact#2]
when click the lastpass icon on toolbar, the toolbar whole move up some pixel
BTW: really nice theme
![screenshot_20160306_102959](https://cloud.githubusercontent.com/assets/153857/13551946/63356b96-e386-11e5-9c39-f1e6bda345f7.png)

**Comment by 3marcusw** [comment]
Does this still happen with firefox 45 and the latest version of the addons? Also, are you using any other appearance addons like Classic Theme Restorer?

**Comment by KalenXI** [comment]
I have the same issue running Firefox 45.0.1 in Windows 7 with Lastpass 3.3.1. The only other addon I have is uBlock Origin. The problem seems limited to Windows and Linux as I don't have the issue in 45.0.1 on my Mac.
